FROM registry.gsc.wustl.edu/sleong/esm:intel-2021.1.2

COPY lsf/ /opt/ibm/lsfsuite/lsf/

# Set MOFED version, OS version and platform
ENV MOFED_VERSION 5.4-3.1.0.0
ENV OS_VERSION rhel7.7
ENV PLATFORM x86_64

# Download and install Mellanox OFED

RUN echo "y" | /usr/sbin/ofed_uninstall.sh && \
    yum install -y libusbx fuse-libs tcl gcc-gfortran tk perl wget pciutils numactl-libs gtk2 atk cairo tcsh lsof libmnl ethtool file sssd epel-release && \
    . /opt/intel/oneapi/common.sh && \
    export PLATFORM=x86_64 && \
    export CC=icc && \
    export CXX=icpc && \
    export FC=ifort && \
    cd /tmp/ && \
    wget -q http://content.mellanox.com/ofed/MLNX_OFED-${MOFED_VERSION}/MLNX_OFED_LINUX-${MOFED_VERSION}-${OS_VERSION}-${PLATFORM}.tgz && \
    . /etc/bashrc && \
    export PLATFORM=x86_64 && \
    tar -xvf MLNX_OFED_LINUX-${MOFED_VERSION}-${OS_VERSION}-${PLATFORM}.tgz && \
    MLNX_OFED_LINUX-${MOFED_VERSION}-${OS_VERSION}-${PLATFORM}/mlnxofedinstall --user-space-only --without-fw-update -q && \
    cd .. && \
    rm -rf /tmp/MLNX_OFED_LINUX-${MOFED_VERSION}-${OS_VERSION}-${PLATFORM} && \
    rm -rf /tmp/*.tgz && \
    yum clean all
